/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 30 -o ./first/sub-01_first-L_Hipp_first -m /home/mateo/fsl/data/first/models_336_bin/intref_thal/L_Hipp.bmv -intref /home/mateo/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-L_Hipp_first -o ./first/sub-01_first-L_Hipp_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 30 -o ./first/sub-01_first-R_Hipp_first -m /home/mateo/fsl/data/first/models_336_bin/intref_thal/R_Hipp.bmv -intref /home/mateo/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-R_Hipp_first -o ./first/sub-01_first-R_Hipp_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 40 -o ./first/sub-01_first-L_Thal_first -m /home/mateo/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-L_Thal_first -o ./first/sub-01_first-L_Thal_corr -i ./brains/sub-01_T1w_brain -b none
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 40 -o ./first/sub-01_first-R_Thal_first -m /home/mateo/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-R_Thal_first -o ./first/sub-01_first-R_Thal_corr -i ./brains/sub-01_T1w_brain -b none
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 30 -o ./first/sub-01_first-L_Caud_first -m /home/mateo/fsl/data/first/models_336_bin/intref_thal/L_Caud.bmv -intref /home/mateo/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-L_Caud_first -o ./first/sub-01_first-L_Caud_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 30 -o ./first/sub-01_first-R_Caud_first -m /home/mateo/fsl/data/first/models_336_bin/intref_thal/R_Caud.bmv -intref /home/mateo/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-R_Caud_first -o ./first/sub-01_first-R_Caud_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 40 -o ./first/sub-01_first-L_Puta_first -m /home/mateo/fsl/data/first/models_336_bin/05mm/L_Puta_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-L_Puta_first -o ./first/sub-01_first-L_Puta_corr -i ./brains/sub-01_T1w_brain -b none
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 40 -o ./first/sub-01_first-R_Puta_first -m /home/mateo/fsl/data/first/models_336_bin/05mm/R_Puta_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-R_Puta_first -o ./first/sub-01_first-R_Puta_corr -i ./brains/sub-01_T1w_brain -b none
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 40 -o ./first/sub-01_first-L_Pall_first -m /home/mateo/fsl/data/first/models_336_bin/05mm/L_Pall_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-L_Pall_first -o ./first/sub-01_first-L_Pall_corr -i ./brains/sub-01_T1w_brain -b none
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 40 -o ./first/sub-01_first-R_Pall_first -m /home/mateo/fsl/data/first/models_336_bin/05mm/R_Pall_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-R_Pall_first -o ./first/sub-01_first-R_Pall_corr -i ./brains/sub-01_T1w_brain -b none
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 50 -o ./first/sub-01_first-L_Amyg_first -m /home/mateo/fsl/data/first/models_336_bin/intref_thal/L_Amyg.bmv -intref /home/mateo/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-L_Amyg_first -o ./first/sub-01_first-L_Amyg_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 50 -o ./first/sub-01_first-R_Amyg_first -m /home/mateo/fsl/data/first/models_336_bin/intref_thal/R_Amyg.bmv -intref /home/mateo/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-R_Amyg_first -o ./first/sub-01_first-R_Amyg_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 50 -o ./first/sub-01_first-L_Accu_first -m /home/mateo/fsl/data/first/models_336_bin/L_Accu_bin.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-L_Accu_first -o ./first/sub-01_first-L_Accu_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 50 -o ./first/sub-01_first-R_Accu_first -m /home/mateo/fsl/data/first/models_336_bin/R_Accu_bin.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-R_Accu_first -o ./first/sub-01_first-R_Accu_corr -i ./brains/sub-01_T1w_brain -b fast
/home/mateo/fsl/bin/run_first -i ./brains/sub-01_T1w_brain -t ./brains/sub-01_T1w_brain_to_std_sub.mat -n 40 -o ./first/sub-01_first-BrStem_first -m /home/mateo/fsl/data/first/models_336_bin/BrStem_bin.bmv; /home/mateo/fsl/bin/first_boundary_corr -s ./first/sub-01_first-BrStem_first -o ./first/sub-01_first-BrStem_corr -i ./brains/sub-01_T1w_brain -b fast
